
server:
  port: 8081

spring:
  datasource:
    username: root
    password: anywhere
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: springboot.hello.helloSpringboot.entity

#Redis
#spring.redis.host=127.0.0.1
redis:
  host: 127.0.0.1
  ## Redis服务器连接端口
  port: 6379
  ## 连接超时时间（毫秒）
  timeout: 3
  ## Redis服务器连接密码（默认为空）
  password: 135246
  ## 连接池中的最大连接数
  poolMaxTotal: 10
  ## 连接池中的最大空闲连接
  poolMaxIdle: 10
  ## 连接池最大阻塞等待时间（使用负值表示没有限制）
  poolMaxWaitP: 3